defaults:
  - experiment: exp3  # デフォルトで "experiment" グループの "hh.yaml" を読み込む
  - _self_ # ショートカット定義は最後に設定

hydra:
  run:
    dir: hydra-outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: hydra-multiruns/${now:%Y-%m-%d_%H-%M-%S}

seed: 6

neurons:
  hh:
    params:
  hh3:
    params:
      G_12: ${g_12}
      G_23: ${g_23}
      G_LEAK: 0.3
      E_LEAK: -54.4
      C: 1.0
      DT: 0.01

models:
  surrogate:
    _target_: neurosurrogate.modeling.surrogate.SINDySurrogate
    feature_lib:
      _target_: neurosurrogate.utils.base_hh.base_hh
    optimizer:
      _target_: pysindy.optimizers.STLSQ
      threshold: 0.01
      normalize_columns: false
      alpha: 2.0
    params:
      G_LEAK: ${neurons.hh3.params.G_LEAK}
      E_LEAK: ${neurons.hh3.params.E_LEAK}
      C: ${neurons.hh3.params.C}
      G_12: ${neurons.hh3.params.G_12}
      G_23: ${neurons.hh3.params.G_23}
      DT: ${neurons.hh3.params.DT}

eval:
  direct: False
  onlyThreeComp : ${sc}


# alias
sc: False
g_12: 1
g_23: 0.7