defaults:
  - experiment: exp3  # デフォルトで "experiment" グループの "hh.yaml" を読み込む
  - _self_ # ショートカット定義は最後に設定

hydra:
  run:
    dir: hydra-outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: hydra-multiruns/${now:%Y-%m-%d_%H-%M-%S}

seed: 6

neurons:
  hh:
  hh3:
    G_12: ${g_12}
    G_23: ${g_23}

simulater_dt: 0.01

models:
  surrogate:
    params:
      DT: ${simulater_dt}

matplotlib_style: paper

# alias
sc: False
g_12: 1
g_23: 0.7