defaults:
  - experiment: exp3  # デフォルトで "experiment" グループの "hh.yaml" を読み込む
  - _self_ # ショートカット定義は最後に設定

hydra:
  run:
    dir: hydra-outputs/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: hydra-multiruns/${now:%Y-%m-%d_%H-%M-%S}

matplotlib_style: paper

seed: 6
simulater_dt: 0.01

neurons:
  hh:
  hh3:
    G_12: 1
    G_23: 0.7